### ISSUE TITLE
Build error when combining with pdf_render

### ISSUE THREAD

**Issue by dickverweij** [espresso3389/flutter_content_resolver#2]
When including content_resolver in to my pubspec:

A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libbbhelper.so' from inputs:
      - C:\Users\dvy\source\repos\afasscanapp\build\pdf_render\intermediates\library_jni\debug\jni\arm64-v8a\libbbhelper.so
      - C:\Users\dvy\source\repos\afasscanapp\build\content_resolver\intermediates\library_jni\debug\jni\arm64-v8a\libbbhelper.so

**Comment by espresso3389** [comment]
Please try [0.2.0](https://pub.dev/packages/content_resolver/versions/0.2.0).
The release has the following changes:
- Rename internal module name (`bbhelper` -> `dbufhelper`) not to conflict with pdf_render
- Update example code to use latest AppLinks plugin

**Comment by dickverweij** [comment]
Thanks!

**Comment by dickverweij** [comment]
Your release works like a charm, now finding how to receive the mime type of the resolved file :-)
